services:
  - type: web
    name: gestion-stock
    env: php
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 public/index.php
    envVars:
      - key: PHP_VERSION
        value: 8.2
    healthCheckPath: /health-check.php